### PR TITLE
A lot of improvments, see commit messages !

### PR DESCRIPTION
**Pull request by kiorky**

### CODE REVIEW

**Comment by mmerickel** [comment]
I have merged this branch with master and pushed it to the [velruse/pull.37](https://github.com/bbangert/velruse/tree/pull.37) branch to make this manageable to think about.

It looks like there's a lot of useful stuff here.

**Comment by mmerickel** [comment]
I'd be interested in making velruse depend on pyramid 1.3a1 in order to utilize its new introspectable api. I'm not really a fan of how this is being handled via `settings['velruse.providers_infos']`.

**Comment by kiorky** [comment]
Remember that explicit is better than implicit !

**Comment by kiorky** [comment]
This pull request has been splitted in lot of later other pull requests

**Pull request closed without merging**
