### PR TITLE
Use namespaced session keys to avoid clashes, and pop after use

### PR DESCRIPTION
**Pull request by asabil**

### CODE REVIEW

**Comment by mmerickel** [comment]
I'm not sure of a use-case where anyone should be trying to login to multiple providers simultaneously but at least `velruse.token` makes sense.

**Comment by asabil** [comment]
I will amend the commit to remove the provider name from the session keys then.

**Comment by asabil** [comment]
Pull request updated

**Comment by invisibleroads** [comment]
I agree with Ali that session variables should be namespaced to prevent conflicts with other plugins.  Thanks, Ali.

**Comment by mmerickel** [comment]
This looks good, sorry for the delay!

**Pull request merged**
