### PR TITLE
Fixes issue #34 and #35

### PR DESCRIPTION
**Pull request by cd34**
removed nose dependency mentioned on ticket #34
converted birthdates to use datetime.date format from ticket #35

### CODE REVIEW

**Comment by wichert** [comment]
Jinx.. I just submmited #39 and #40 for the same thing. Main differences between my version and these are:
- #39 also adds test dependencies for pymongo and routes, which are used during tests
- #40 tries to be robust against invalid dates

**Comment by cd34** [comment]
I debated whether to do more validation on the date coming back. I think it is probably better to have it as a sanity check. I actually saw the ticket after I hit a use case for it. :)

If you want, remove nose from setup.py and I'll close this commit and you can roll it all up in your pull.

**Comment by wichert** [comment]
I did a cleaup of setup.py in a separate pull request: #39

## 

Wichert Akkerman wichert@wiggy.net   It is simple to make things.
http://www.wiggy.net/                  It is hard to make things simple.

**Comment by cd34** [comment]
pull replaced by wichert's pull, closing.

**Pull request closed without merging**
