### PR TITLE
register all provider views with NO_PERMISSION_REQUIRED

### PR DESCRIPTION
**Pull request by ergo**
register all provider views with NO_PERMISSION_REQUIRED, required for
pyramid apps that set default permission for all other views via configurator

### CODE REVIEW

**Comment by mmerickel** [comment]
Before I attempt to think about this, was it not necessary to add the permission to the callback URL as well?

**Comment by ergo** [comment]
Well you need to add a new view for authentication context to your config anyways, so you set the permission there:

config.add_view('myapp.user:oauth_connect',
                    context='velruse.api.AuthenticationComplete',
                    renderer='string',
                    permission='**no_permission_required**'
                    )

before the changes in this pull, i had to register everything for every provider

**Comment by mmerickel** [comment]
Oh duh, glad I made it clear that I didn't think before asking. :-) How about if I support config.add_facebook_login(..., permission=NO_PERMISSION_REQUIRED). The reason would be that you could use the login view with an already-authenticated user to escalate their facebook privileges or something. Do you think this makes sense?

**Comment by ergo** [comment]
im not sure to be honest, you will have to call /facebook/login for "anything" so both logged and unlogged - so i think that you still need to pass NO_PERMISSION_REQUIRED for whatever situation you have in mind (otherwise you cant register new users with external identity), and maybe when you need to do permission escalation that would be handled on context factory level - but thats a guess right now. Im fine with any option as long i dont have to set up every view explictly ;-)

**Pull request merged**
