### PR TITLE
fix #86 - Add state passing for github provider

### LINKED ISSUE #86: Add state passing for github provider
initial authorize call requires to use "state" param otherwise github throws in response 404

### PR DESCRIPTION
**Pull request by ergo**

### CODE REVIEW

**Comment by mmerickel** [comment]
thanks!

**Comment by naktinis** [comment]
Why does it have to pass uuid in state parameter? What if I wanted to pass custom information in state?

**Comment by ergo** [comment]
Because the purpose of state field is to carry some unguessable value that you can check later to make sure the original request came from your application and authenticate it, uuid is perfect for this.

**Comment by naktinis** [comment]
The OAuth 2.0 specs (http://tools.ietf.org/html/draft-ietf-oauth-v2-31#section-3.1.2.2) also say:
"The authorization server SHOULD require the client to provide the
complete redirection URI (the client MAY use the "state" request
parameter to achieve per-request customization)."

Although specs suggest the state parameter SHOULD (not MUST - http://tools.ietf.org/html/rfc2119) "be used for preventing cross-site request forgery", they don't say it should be used ONLY for that purpose. I.e. it can be used to contain uuid or any other information, or both uuid AND other information.

**Comment by ergo** [comment]
I suggest that you put "other information" to session storage if you need it - like we do with state field, thus archiving same result.

**Comment by mmerickel** [comment]
@ergo is correct, custom user-specified state in velruse should be done in the session storage instead of passing it back and forth to the third-party provider. This is along the lines of what #65 wants to accomplish.

**Pull request merged**
