### PR TITLE
load more data from twitter (and photo from linkedin)

### PR DESCRIPTION
**Pull request by keul**
Twitter (and linkedin) providers can load more user data.

I'm still keeping the Portable Contacts format. for twitter, I need to perform another call to the twitter remote service.

### CODE REVIEW

**Comment by keul** [comment]
This PR can't be closed due to recent changes. Meanwhile twitter implementation has changed.

You can find new implementation (with 1.1. API) there: https://github.com/RedTurtle/velruse/tree/more-twitter-data

**Comment by mmerickel** [comment]
Last night I replaced the python-oauth2 code with requests_oauthlib. All tests pass for me on master. If you can update your PR to support the updates I'll be happy to merge this update.

**Comment by keul** [comment]
Amazing! I'll fix the pull request ASAP, probably I'll create a new one.

**Comment by mmerickel** [comment]
This PR has been replaced by #120 and #121.

**Pull request closed without merging**
